# fly.toml app configuration file generated for smart-productos-pet-white-waterfall-8585-restless-shape-6437 on 2024-01-03T23:48:12-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "smart-productos-pet-white-waterfall-8585-restless-shape-6437"
primary_region = "eze"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
