# fly.toml app configuration file generated for smart-productos-pet-shy-lake-994 on 2023-12-23T12:24:18-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "smart-productos-pet-shy-lake-994"
primary_region = "eze"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
